<?php define('BASE', '../');?>
<?php define('PAGE', 'experiencia');?>
<?php include(BASE.'header.php'); ?>
<?php include(BASE.'slider.php'); ?>
<?php include(BASE.'que_hacemos.php'); ?>
<?php include(BASE.'experiencia.php'); ?>
<?php include(BASE.'clientes.php'); ?>
<?php include(BASE.'contacto.php'); ?>
<?php include(BASE.'footer.php'); ?>